# This code was generated by ChatGPT

# Run with: sage -python file.py
from sage.all import *
from time import perf_counter

import solids_prep.solids_dict_prep as sdp

def normalize(c):
    d, r, k = {}, [], 0
    for x in c:
        if x not in d:
            d[x] = k
            k += 1
        r.append(d[x])
    return tuple(r)

def canon_under_aut(c, perms):
    n = len(c)
    best = None

    for p in perms:
        img = [0] * n
        for v in range(n):
            img[p[v]] = c[v]

        t = normalize(img)
        if best is None or t < best:
            best = t

    return best

def unlabeled_colorings_up_to_aut(G, q, verbose=True, report_every=10000):
    V = list(G.vertices())
    mp = {v: i for i, v in enumerate(V)}

    H = Graph()
    H.add_vertices(range(len(V)))
    H.add_edges((mp[u], mp[v]) for u, v in G.edges(labels=False))

    n = H.order()

    N = [0] * n
    for v in range(n):
        for u in H.neighbors(v):
            N[v] |= 1 << u

    order = sorted(range(n), key=lambda v: H.degree(v), reverse=True)
    perms = [[a(v) for v in range(n)] for a in H.automorphism_group()]

    reps = set()
    c = [-1] * n
    color_masks = [0] * q

    nodes = 0
    leaves = 0
    proper_surjective = 0
    pruned_too_many = 0
    pruned_too_few = 0
    pruned_adjacency = 0

    t0 = perf_counter()
    last_report = t0

    def report(i, used, force=False):
        nonlocal last_report
        now = perf_counter()

        if not force and nodes % report_every != 0:
            return

        last_report = now
        print(
            f"q={q} | "
            f"nodes={nodes} | "
            f"depth={i}/{n} | "
            f"used={used}/{q} | "
            f"proper_surjective={proper_surjective} | "
            f"orbits_found={len(reps)} | "
            f"pruned: too_many={pruned_too_many}, "
            f"too_few={pruned_too_few}, "
            f"adjacency={pruned_adjacency} | "
            f"time={now - t0:.2f}s",
            flush=True
        )

    def backtrack(i, used):
        nonlocal nodes, leaves, proper_surjective
        nonlocal pruned_too_many, pruned_too_few, pruned_adjacency

        nodes += 1

        if verbose:
            report(i, used)

        if used > q:
            pruned_too_many += 1
            return

        if used + (n - i) < q:
            pruned_too_few += 1
            return

        if i == n:
            leaves += 1
            if used == q:
                proper_surjective += 1
                reps.add(canon_under_aut(c, perms))
            return

        v = order[i]

        for col in range(used):
            if color_masks[col] & N[v]:
                pruned_adjacency += 1
                continue

            c[v] = col
            color_masks[col] |= 1 << v

            backtrack(i + 1, used)

            color_masks[col] ^= 1 << v
            c[v] = -1

        if used < q:
            c[v] = used
            color_masks[used] = 1 << v

            backtrack(i + 1, used + 1)

            color_masks[used] = 0
            c[v] = -1

    if verbose:
        print(f"\nStarting q={q}")
        print(f"vertices={n}, edges={H.size()}, |Aut(G)|={len(perms)}")
        print(f"vertex_order={order}")

    backtrack(0, 0)

    if verbose:
        report(n, q, force=True)
        print(
            f"Finished q={q}: result={len(reps)}, "
            f"proper_surjective={proper_surjective}, "
            f"leaves={leaves}, nodes={nodes}, "
            f"time={perf_counter() - t0:.2f}s\n"
        )

    return len(reps)



# SOLID SETTINGS
SOLID_NAME = "truncated octahedron"
NUM_CLRS = 3

# GRAPH DATA
G = Graph(sdp.get_all_solids_dict()[SOLID_NAME][sdp.JSON_EDGES])
# G = graphs.PetersenGraph()
for q in range(2,9):
    print(q, unlabeled_colorings_up_to_aut(G, q))